# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
name: "Test"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
on:
  push:
    branches:
      - "master"
  pull_request:
    types:
      - synchronize
      - opened

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
jobs:

  test:
    strategy:
      matrix:
        environment: [ ubuntu-latest, windows-latest, macos-latest ]
        node: [ 10, 12, 14 ]

    name: "Node ${{ matrix.node }} on ${{ matrix.environment }}"
    runs-on: ${{ matrix.environment }}
    steps:

      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: "Setup Node Environment"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: "Install Dependencies"
        run: npm install -m

      - name: "Test"
        run: npm run mocha
